language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit -v --coverage-clover clover
