<?php 

// This file is generated by Composer
require_once 'vendor/autoload.php';

$api = \Zimbra\Admin\AdminFactory::instance('https://mail.saoleopoldo.rs.gov.br:7071/service/admin/soap');
//$api->auth('username', 'password');
$api->auth('andre', '281079cd');
//$account = new \Zimbra\Struct\AccountSelector(\Zimbra\Enum\AccountBy::NAME(), 'username');
$account = new \Zimbra\Struct\AccountSelector(\Zimbra\Enum\AccountBy::NAME(), 'andre');
$accountInfo = $api->getAccountInfo($account);

//$getAccountDistributionLists = $api->getAccountDistributionLists($account);
//$changePassword = $api->changePassword($account);
//$distributionList = new \Zimbra\Admin\Struct\DistributionListSelector(\Zimbra\Enum\DistributionListBy::NAME(), 'prefeiturasl');
//$createAccount = $api->createAccount('zimbra.api@saoleopoldo.rs.gov.br');
//$deleteAccount = $api->deleteAccount('b0e55398-fe52-4ce7-a5e8-f85252a7ce5e');
print_r($accountInfo);
 ?>